CREATE TABLE IF NOT EXISTS 'users' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'username' TEXT NOT NULL, 'hash' TEXT NOT NULL, 'cash' NUMERIC NOT NULL DEFAULT 10000.00 );
CREATE UNIQUE INDEX 'username' ON "users" ("username");
CREATE TABLE IF NOT EXISTS 'companies' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'symbol' TEXT NOT NULL, 'name' TEXT NOT NULL);
CREATE UNIQUE INDEX 'symbol' ON "companies" ("symbol");
CREATE UNIQUE INDEX 'name' ON "companies" ("name");
CREATE TABLE IF NOT EXISTS 'transactions' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'user' INTEGER NOT NULL, 'company' INTEGER NOT NULL, 'cost' INTEGER NOT NULL, 'shares' INTEGER NOT NULL, 'datetime' TEXT NOT NULL, FOREIGN KEY (user) REFERENCES users (id), FOREIGN KEY (company) REFERENCES companies (id));
